### ISSUE TITLE
Error: Message: element not interactable

### ISSUE THREAD

**Issue by freeutka** [xdearboy/pastecreator#2]
@admin ➜ /pastecreater $~ Choose an interface (CLI/GUI): cli
@admin ➜ /pastecreater $~ Write the content of the paste  : Test paste 123321
@admin ➜ /pastecreater $~ Write the title of the paste: vgbte

DevTools listening on ws://127.0.0.1:59069/devtools/browser/f7047f6d-8a0b-4fa9-ba22-68d89629fbfd
Error: Message: element not interactable
  (Session info: chrome=126.0.6478.61)
Stacktrace:
        GetHandleVerifier [0x00420E73+27667]
        (No symbol) [0x003B6B74]
        (No symbol) [0x002B197D]
        (No symbol) [0x002EDA09]
        (No symbol) [0x002EC355]
        (No symbol) [0x0031392C]
        (No symbol) [0x002E8BA5]
        (No symbol) [0x00313BC4]
        (No symbol) [0x0032CAC7]
        (No symbol) [0x003136C6]
        (No symbol) [0x002E74D1]
        (No symbol) [0x002E804D]
        GetHandleVerifier [0x006D3D03+2857635]
        GetHandleVerifier [0x00727E6D+3202061]
        GetHandleVerifier [0x004A4674+566292]
        GetHandleVerifier [0x004AB86C+595468]
        (No symbol) [0x003BF964]
        (No symbol) [0x003BC678]
        (No symbol) [0x003BC817]
        (No symbol) [0x003AE70E]
        BaseThreadInitThunk [0x75D2FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77E27CBE+286]
        RtlGetAppContainerNamedObjectPath [0x77E27C8E+238]

**Comment by xdearboy** [comment]
посмотри телеграмм
